export const ICON_NAMES = [
  "layoutDashboard",
  "building2",
  "clipboardList",
  "users",
  "creditCard",
  "target",
  "scrollText",
  "headphones",
  "briefcase",
  "barChart3",
  "percent",
  "handCoins",
  "trendingUp",
  "receipt",
  "wallet",
  "lineChart",
  "megaphone",
  "mapPin",
  "userCircle",
  "stethoscope",
  "truck",
  "folderOpen",
  "sparkles",
  "landmark",
  "package",
  "fileText",
  "shield",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
